version: "3"

services:
  dynamodb-manager:
    image: taydy/dynamodb-manager
    ports:
      - "9100:80"
    privileged: true
    restart: always
    networks:
      - aws-local
  dynamodb-local:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - .dbdata:/home/dynamodblocal/data
    restart: always
    ports:
      - "9101:8000"
    restart: always
    networks:
      - aws-local

networks:
  aws-local: